import os, glob

# import root environment
Import( ["buildenv", "installer"])
myenv = buildenv.Clone()

# get all the sourcefiles
cpps = myenv.Glob("*.cc")
# need this to go to the root dir, as SConsript asumes to be in the
# build dir

libname = "casa_casa"

slib =  myenv.StaticLibrary(target = libname, source = [cpps])
myenv.Alias(os.path.basename(os.path.normpath(str(slib[0]))), slib)
myenv.Alias("static", slib)
myenv.Default("static")


rootdir = myenv.Dir("#").abspath
# install headers, only works with absolute dir.
installer.AddHeaders( rootdir+"/casa", "*.h", "casacore/casa/", True )
installer.AddHeaders( rootdir+"/casa", "*.tcc", "casacore/casa/", True )
