import os

# import root environment
Import( ["buildenv", "installer"])
myenv = buildenv.Clone()

# get all the sourcefiles recursively
lls = myenv.SGlob("*.ll", recursive=True )

for f in lls:
    myenv.CXXFile(f, CXXFILESUFFIX=".lcc")
    path = os.path.split(f)[0]
    myenv.AppendUnique(CPPPATH=[Dir(path)])

yys = myenv.SGlob("*.yy", recursive=True )
for f in yys:
    myenv.CXXFile(f, CXXFILESUFFIX=".ycc")


cpps = myenv.SGlob("*.cc", excludedirs=["test"], recursive=True )

# need this to go to the root dir, as SConsript asumes to be in the
# build dir
rootdir = myenv.Dir("#").abspath
libname = "casa_tables"

myenv.AppendUnique(LIBS=["casa_casa"])

slib =  myenv.StaticLibrary(target = libname, source = [cpps])
myenv.Alias(os.path.basename(os.path.normpath(str(slib[0]))), slib)
myenv.Alias("static", slib)
myenv.Default("static")

testenv = myenv.Clone()
# gather test files
# SGlob works in build dir, so only for cc files
ttests = testenv.SGlob("Tables/test/*.cc")
lttests = testenv.SGlob("LogTables/test/*.cc")
# point to tests local includes
testenv.PrependUnique(LIBPATH=[testenv["BUILDDIR"]])
# allow either linking against shared or static, static if both present
testenv.PrependUnique(LIBS=slib)
testenv2 = testenv.Clone()
# add files necessary for testing which are not names tXYZ.*
testenv["ASSAYAUX"] = testenv.SGlob("*/test/*.data_v*")
map(testenv.addAssayTest, ttests)
map(testenv2.addAssayTest, lttests)


# install headers, only works with absolute dir.
installer.AddHeaders( rootdir+"/tables", "*.h", "casacore", True )
installer.AddHeaders( rootdir+"/tables", "*.tcc", "casacore", True )
