import os

# import root environment
Import( ["buildenv", "installer"])
myenv = buildenv.Clone()
# add custom test auxiliary files
myenv["ASSAYAUX"] = myenv.SGlob("*/test/*.data_v*")
myenv.CasaBuilder(installer=installer)
