#!/usr/bin/env python

import re
import sys

# This script compares two text files for equality.
# If numbers mismatch, it is checked if they are near each other.
# The tolerance can be given as the third argument; it defaults to 1e-5.

def splitfile (filename, regexp):
    f = open(filename, 'r')
    res = []
    for line in f:
        # Make sure numbers are separated by blanks.
        line = regexp.sub (' \g<grp> ', line)
        res.extend (line.split())
    f.close()
    return res;

def near (val1, val2, tol):
    if val1 == 0:
        return abs(val2) <= (1+tol)*1e-30
    if val2 == 0:
        return abs(val1) <= (1+tol)*1e-30
    if (val1>0) != (val2>0):
        return False
    return abs(val1-val2) <= tol*max(abs(val1),abs(val2))

def main(argv=None):
    if argv is None:
        argv = sys.argv
    if len(argv) < 3:
        print sys.stderr, 'run as:   floatcheck.py file1 file2 [tolerance]'
        return 1
    tol = 1e-5;
    if len(argv) > 3:
        tol = float(argv[3])

    # Regular expression for an integer or float number.
    numre = re.compile ('(?P<grp>[+-]?([0-9]+\.[0-9]*|[0-9]*\.[0-9]+|[0-9]+)([ed][+-][0-9]+)?)', re.IGNORECASE)

    # Split file in separate values.
    res1 = splitfile (argv[1], numre);
    res2 = splitfile (argv[2], numre);

    # Keep list of possible numbers to compare.
    num1 = []
    num2 = []
    # Compare res1 and res2 for equality.
    # Mismatching numbers are kept and compared later.
    print len(res1), res1
    print len(res2), res2
    if len(res1) != len(res2):
        return 1      # mismatch
    for i in range(len(res1)):
        if res1[i] != res2[i]:
            if numre.sub('', res1[i]) != ''  or  numre.sub('', res2[i]) != '':
                return 1
            num1.append (res1[i])
            num2.append (res2[i])

    # Now compare if numbers are more or less equal.
    for i in range(len(num1)):
        print num1[i], num2[i]
        val1 = float(num1[i])
        val2 = float(num2[i])
        if not near(val1, val2, tol):
            return 2
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
